# Generated by Django 3.2.15 on 2023-09-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('packing', 'Готовится'), ('delivery', 'Передан в доставку'), ('done', 'Завершен')], db_index=True, default='В обработке', max_length=50, verbose_name='статус'),
        ),
    ]
