# Generated by Django 3.2.15 on 2023-09-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20230919_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('unknown', 'Не указан'), ('cash', 'Наличные'), ('card', 'Карта')], db_index=True, default='Не указан', max_length=50, verbose_name='способ оплаты'),
        ),
    ]
